# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Telophasecli < Formula
  desc "Open-Source AWS Control Tower"
  homepage "https://github.com/Santiago-Labs/telophasecli"
  version "0.5.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Santiago-Labs/telophasecli/releases/download/v0.5.0/telophasecli_Darwin_x86_64.tar.gz"
      sha256 "d29bae2b115a74ef2012c5549713957c033a021231f27c6acc44ab1dead34530"

      def install
        bin.install "telophasecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Santiago-Labs/telophasecli/releases/download/v0.5.0/telophasecli_Darwin_arm64.tar.gz"
      sha256 "77f160d51ed3c5da1a73e3b01273011fa9441029c0599a0e53b3eb0b1d440955"

      def install
        bin.install "telophasecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Santiago-Labs/telophasecli/releases/download/v0.5.0/telophasecli_Linux_x86_64.tar.gz"
      sha256 "76c0eba16f787ecb94cd42c96308c8c12e68c704f7c21a4afd6100953d6fd3cf"

      def install
        bin.install "telophasecli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Santiago-Labs/telophasecli/releases/download/v0.5.0/telophasecli_Linux_arm64.tar.gz"
      sha256 "4123dc25cddc8c5adeeea749db89c1736592c69276c25f11ac78128354c5c318"

      def install
        bin.install "telophasecli"
      end
    end
  end
end
