# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Telophasecli < Formula
  desc "Open-Source AWS Control Tower"
  homepage "https://github.com/Santiago-Labs/telophasecli"
  version "0.3.6"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Santiago-Labs/telophasecli/releases/download/v0.3.6/telophasecli_Darwin_x86_64.tar.gz"
      sha256 "d402bd3e3d678cf93a298ae7f549792d264ee2c22b6ab385e96e0fd94cd6a9e4"

      def install
        bin.install "telophasecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Santiago-Labs/telophasecli/releases/download/v0.3.6/telophasecli_Darwin_arm64.tar.gz"
      sha256 "9d041c1b51d143c9d711ee054baabbe2b981b3dbed4eaf4dfa0f84ce1b7b590a"

      def install
        bin.install "telophasecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Santiago-Labs/telophasecli/releases/download/v0.3.6/telophasecli_Linux_x86_64.tar.gz"
      sha256 "9809c38246bedd29518f63caef4f5b26198d00f8e1a6f067bcabbc2ef34898d5"

      def install
        bin.install "telophasecli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Santiago-Labs/telophasecli/releases/download/v0.3.6/telophasecli_Linux_arm64.tar.gz"
      sha256 "807cd7acecefa852964c12149761bdc162b848ea317d5ee5b20e65c16ea18829"

      def install
        bin.install "telophasecli"
      end
    end
  end
end
